"""delete seller_id column in transaction model

Revision ID: 45ee15e9f9a1
Revises: 1c68845d925e
Create Date: 2024-08-12 22:19:24.388815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45ee15e9f9a1'
down_revision = '1c68845d925e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('transactions_ibfk_2', type_='foreignkey')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('transactions_ibfk_2', 'sellers', ['seller_id'], ['id'])

    # ### end Alembic commands ###
