"""add invoice column

Revision ID: a0b08c35d3dd
Revises: a6082c02eda7
Create Date: 2024-08-14 23:09:45.417853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0b08c35d3dd'
down_revision = 'a6082c02eda7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice', sa.String(length=255), nullable=True))
        batch_op.alter_column('seller_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'sellers', ['seller_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('seller_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('invoice')

    # ### end Alembic commands ###
