"""welcome back seller_id to transaction model

Revision ID: a6082c02eda7
Revises: 45ee15e9f9a1
Create Date: 2024-08-14 19:54:19.732874

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a6082c02eda7"
down_revision = "45ee15e9f9a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('transactions', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=False))
    #     batch_op.create_foreign_key(None, 'sellers', ['seller_id'], ['id'])
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("seller_id")

    # ### end Alembic commands ###
